### PR TITLE
accept PTY options

### PR DESCRIPTION
**Pull request by bjmllr**
My use case for this is sending an explicit terminal type. I have some systems that insert ansi codes in the prompt, which prevents my prompt regexp from matching them.

This gem is fantastic, by the way. :heart:

### CODE REVIEW

**Comment by jasonkarns** [comment]
I am not an author of this gem (nor even a maintainer). This was forked from the rubyforge git repo for my own branching purposes. However, I don't intend to maintain the gem itself or commit anything to master.

**Comment by bjmllr** [comment]
Ah, my mistake! Thanks for the clarification!

**Comment by jasonkarns** [comment]
No worries. I need to update the description and add a note to the readme.
(Though that would involve setting a non-master branch to be default, since
I am intentionally avoiding committing on master. :) )

**Comment by bjmllr** [comment]
@mdkent Are you maintaining this gem still?

**Comment by mdkent** [comment]
No sorry, I'm pretty short of time on a consistent basis. If anyone would like to take it over that'd be great.

**Pull request closed without merging**
